### PR TITLE
add keyed list type to support hash-map style updaters

### PR DESCRIPTION
**Pull request by sojournerc**
Hey Greg, 

I hope all is well at the new gig. 

I added a new type here to support a hash-map style updater, where arrays of urls are updated, but are allowed to have arbitrary/dynamic keys for the returned values. 

Thanks,

Chris M

### CODE REVIEW

**Comment by greim** [comment]
Cool. Want me to re-publish to npm too? Probably need to figure out how to share or transfer npm publish rights.

**Comment by greim** [comment]
Also, I made you a collaborator a few weeks ago, so you should be able to commit to this repo directly if you want.

**Comment by sojournerc** [comment]
Awesome, thanks Greg.

If you wouldn't mind publishing to NPM that would be appreciated - not sure
on how to change ownership.

On Mon, Nov 9, 2015 at 2:41 PM, Greg Reimer <notifications@github.com>
wrote:

> Also, I made you a collaborator a few weeks ago, so you should be able to
> commit to this repo directly if you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greim/stoar/pull/1#issuecomment-155207009>.
>



-- 
Christopher Meyer
Meyer Creative Enterprises, LLC.
303.513.1956
@Chris_Paul_M

**Comment by greim** [comment]
Cool. 0.2.3 is published now.

**Comment by greim** [comment]
Ah, here: https://docs.npmjs.com/cli/owner

Ping me your npm username and I'll add you.

**Comment by sojournerc** [comment]
Thanks so much Greg,

My npm user is:  sojournerc

On Mon, Nov 9, 2015 at 3:16 PM, Greg Reimer <notifications@github.com>
wrote:

> Ah, here: https://docs.npmjs.com/cli/owner
>
> Ping me your npm username and I'll add you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greim/stoar/pull/1#issuecomment-155216427>.
>



-- 
Christopher Meyer
Meyer Creative Enterprises, LLC.
303.513.1956
@Chris_Paul_M

**Comment by greim** [comment]
Done!

If you publish the current contents of master and have permission it should err out with an "already published" error. Otherwise it would be a "permission denied" error (I think). Anyway let me know if that doesn't work.

**Pull request merged**
